import { TOGAFTerm, TermCategory } from "./types";

export const iso9000Terms: TOGAFTerm[] = [
  {
    id: "iso1",
    english: "Quality",
    spanish: "Calidad",
    englishDefinition: "degree to which a set of inherent characteristics fulfills requirements",
    spanishDefinition: "grado en el que un conjunto de características inherentes cumple con los requisitos",
    reference: "ISO 9000 §3.1.1",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso2",
    english: "Requirement",
    spanish: "Requisito",
    englishDefinition: "need or expectation that is stated, generally implied or obligatory",
    spanishDefinition: "necesidad o expectativa establecida, generalmente implícita u obligatoria",
    reference: "ISO 9000 §3.1.2",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso3",
    english: "Grade",
    spanish: "Clase",
    englishDefinition: "category or rank given to different quality requirements for products, processes or systems having the same functional use",
    spanishDefinition: "categoría o rango dado a diferentes requisitos de la calidad para productos, procesos o sistemas que tienen el mismo uso funcional",
    reference: "ISO 9000 §3.1.3",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso4",
    english: "Customer satisfaction",
    spanish: "Satisfacción del cliente",
    englishDefinition: "customer's perception of the degree to which the customer's requirements have been fulfilled",
    spanishDefinition: "percepción del cliente sobre el grado en que se han cumplido sus requisitos",
    reference: "ISO 9000 §3.1.4",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso5",
    english: "Capability",
    spanish: "Capacidad",
    englishDefinition: "ability of an organization, system or process to realize a product that fulfills the requirements for that product",
    spanishDefinition: "aptitud de una organización, sistema o proceso para realizar un producto que cumple los requisitos para ese producto",
    reference: "ISO 9000 §3.1.5",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso6",
    english: "Competence",
    spanish: "Competencia",
    englishDefinition: "demonstrated ability to apply knowledge and skills",
    spanishDefinition: "aptitud demostrada para aplicar los conocimientos y habilidades",
    reference: "ISO 9000 §3.1.6",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso7",
    english: "System",
    spanish: "Sistema",
    englishDefinition: "set of interrelated or interacting elements",
    spanishDefinition: "conjunto de elementos mutuamente relacionados o que interactúan",
    reference: "ISO 9000 §3.2.1",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso8",
    english: "Management system",
    spanish: "Sistema de gestión",
    englishDefinition: "system to establish policy and objectives and to achieve those objectives",
    spanishDefinition: "sistema para establecer la política y los objetivos y para lograr dichos objetivos",
    reference: "ISO 9000 §3.2.2",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso9",
    english: "Quality management system",
    spanish: "Sistema de gestión de la calidad",
    englishDefinition: "management system to direct and control an organization with regard to quality",
    spanishDefinition: "sistema de gestión para dirigir y controlar una organización con respecto a la calidad",
    reference: "ISO 9000 §3.2.3",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso10",
    english: "Quality policy",
    spanish: "Política de la calidad",
    englishDefinition: "overall intentions and direction of an organization related to quality as formally expressed by top management",
    spanishDefinition: "intenciones globales y orientación de una organización relativas a la calidad tal como se expresan formalmente por la alta dirección",
    reference: "ISO 9000 §3.2.4",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso11",
    english: "Quality objective",
    spanish: "Objetivo de la calidad",
    englishDefinition: "something sought, or aimed for, related to quality",
    spanishDefinition: "algo ambicionado, o pretendido, relacionado con la calidad",
    reference: "ISO 9000 §3.2.5",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso12",
    english: "Management",
    spanish: "Gestión",
    englishDefinition: "coordinated activities to direct and control an organization",
    spanishDefinition: "actividades coordinadas para dirigir y controlar una organización",
    reference: "ISO 9000 §3.2.6",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso13",
    english: "Quality management",
    spanish: "Gestión de la calidad",
    englishDefinition: "coordinated activities to direct and control an organization with regard to quality",
    spanishDefinition: "actividades coordinadas para dirigir y controlar una organización en lo relativo a la calidad",
    reference: "ISO 9000 §3.2.8",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso14",
    english: "Quality planning",
    spanish: "Planificación de la calidad",
    englishDefinition: "part of quality management focused on setting quality objectives and specifying necessary operational processes and related resources to fulfill the quality objectives",
    spanishDefinition: "parte de la gestión de la calidad enfocada al establecimiento de los objetivos de la calidad y a la especificación de los procesos operativos necesarios y de los recursos relacionados para cumplir los objetivos de la calidad",
    reference: "ISO 9000 §3.2.9",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso15",
    english: "Quality control",
    spanish: "Control de la calidad",
    englishDefinition: "part of quality management focused on fulfilling quality requirements",
    spanishDefinition: "parte de la gestión de la calidad orientada al cumplimiento de los requisitos de la calidad",
    reference: "ISO 9000 §3.2.10",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso16",
    english: "Quality assurance",
    spanish: "Aseguramiento de la calidad",
    englishDefinition: "part of quality management focused on providing confidence that quality requirements will be fulfilled",
    spanishDefinition: "parte de la gestión de la calidad orientada a proporcionar confianza en que se cumplirán los requisitos de la calidad",
    reference: "ISO 9000 §3.2.11",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso17",
    english: "Quality improvement",
    spanish: "Mejora de la calidad",
    englishDefinition: "part of quality management focused on increasing the ability to fulfill quality requirements",
    spanishDefinition: "parte de la gestión de la calidad orientada a aumentar la capacidad de cumplir con los requisitos de la calidad",
    reference: "ISO 9000 §3.2.12",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso18",
    english: "Continual improvement",
    spanish: "Mejora continua",
    englishDefinition: "recurring activity to increase the ability to fulfill requirements",
    spanishDefinition: "actividad recurrente para aumentar la capacidad para cumplir los requisitos",
    reference: "ISO 9000 §3.2.13",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso19",
    english: "Effectiveness",
    spanish: "Eficacia",
    englishDefinition: "extent to which planned activities are realized and planned results achieved",
    spanishDefinition: "grado en que se realizan las actividades planificadas y se alcanzan los resultados planificados",
    reference: "ISO 9000 §3.2.14",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso20",
    english: "Efficiency",
    spanish: "Eficiencia",
    englishDefinition: "relationship between the result achieved and the resources used",
    spanishDefinition: "relación entre el resultado alcanzado y los recursos utilizados",
    reference: "ISO 9000 §3.2.15",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso21",
    english: "Organization",
    spanish: "Organización",
    englishDefinition: "group of people and facilities with an arrangement of responsibilities, authorities and relationships",
    spanishDefinition: "conjunto de personas e instalaciones con una disposición de responsabilidades, autoridades y relaciones",
    reference: "ISO 9000 §3.3.1",
    category: TermCategory.DEFINITIONS,
    domain: "Business",
    source: "ISO 9000"
  },
  {
    id: "iso22",
    english: "Organizational structure",
    spanish: "Estructura de la organización",
    englishDefinition: "arrangement of responsibilities, authorities and relationships between people",
    spanishDefinition: "disposición de responsabilidades, autoridades y relaciones entre el personal",
    reference: "ISO 9000 §3.3.2",
    category: TermCategory.DEFINITIONS,
    domain: "Business",
    source: "ISO 9000"
  },
  {
    id: "iso23",
    english: "Infrastructure",
    spanish: "Infraestructura",
    englishDefinition: "system of facilities, equipment and services needed for the operation of an organization",
    spanishDefinition: "sistema de instalaciones, equipos y servicios necesarios para el funcionamiento de una organización",
    reference: "ISO 9000 §3.3.3",
    category: TermCategory.DEFINITIONS,
    domain: "Technology",
    source: "ISO 9000"
  },
  {
    id: "iso24",
    english: "Work environment",
    spanish: "Ambiente de trabajo",
    englishDefinition: "set of conditions under which work is performed",
    spanishDefinition: "conjunto de condiciones bajo las cuales se realiza el trabajo",
    reference: "ISO 9000 §3.3.4",
    category: TermCategory.DEFINITIONS,
    domain: "Technology",
    source: "ISO 9000"
  },
  {
    id: "iso25",
    english: "Customer",
    spanish: "Cliente",
    englishDefinition: "organization or person that receives a product",
    spanishDefinition: "organización o persona que recibe un producto",
    reference: "ISO 9000 §3.3.5",
    category: TermCategory.DEFINITIONS,
    domain: "Business",
    source: "ISO 9000"
  },
  {
    id: "iso26",
    english: "Supplier",
    spanish: "Proveedor",
    englishDefinition: "organization or person that provides a product",
    spanishDefinition: "organización o persona que proporciona un producto",
    reference: "ISO 9000 §3.3.6",
    category: TermCategory.DEFINITIONS,
    domain: "Business",
    source: "ISO 9000"
  },
  {
    id: "iso27",
    english: "Interested party",
    spanish: "Parte interesada",
    englishDefinition: "person or group having an interest in the performance or success of an organization",
    spanishDefinition: "persona o grupo que tenga un interés en el desempeño o éxito de una organización",
    reference: "ISO 9000 §3.3.7",
    category: TermCategory.DEFINITIONS,
    domain: "Business",
    source: "ISO 9000"
  },
  {
    id: "iso28",
    english: "Contract",
    spanish: "Contrato",
    englishDefinition: "binding agreement",
    spanishDefinition: "acuerdo vinculante",
    reference: "ISO 9000 §3.3.8",
    category: TermCategory.DEFINITIONS,
    domain: "Business",
    source: "ISO 9000"
  },
  {
    id: "iso29",
    english: "Process",
    spanish: "Proceso",
    englishDefinition: "set of interrelated or interacting activities which transforms inputs into outputs",
    spanishDefinition: "conjunto de actividades mutuamente relacionadas o que interactúan, las cuales transforman elementos de entrada en resultados",
    reference: "ISO 9000 §3.4.1",
    category: TermCategory.DEFINITIONS,
    domain: "Business",
    source: "ISO 9000"
  },
  {
    id: "iso30",
    english: "Product",
    spanish: "Producto",
    englishDefinition: "result of a process",
    spanishDefinition: "resultado de un proceso",
    reference: "ISO 9000 §3.4.2",
    category: TermCategory.DEFINITIONS,
    domain: "Business",
    source: "ISO 9000"
  },
  {
    id: "iso31",
    english: "Objective evidence",
    spanish: "Evidencia objetiva",
    englishDefinition: "data supporting the existence or verity of something",
    spanishDefinition: "datos que respaldan la existencia o veracidad de algo",
    reference: "ISO 9000 §3.8.1",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso32",
    english: "Audit",
    spanish: "Auditoría",
    englishDefinition: "systematic, independent and documented process for obtaining audit evidence and evaluating it objectively to determine the extent to which audit criteria are fulfilled",
    spanishDefinition: "proceso sistemático, independiente y documentado para obtener evidencias de la auditoría y evaluarlas de manera objetiva con el fin de determinar el grado en que se cumplen los criterios de auditoría",
    reference: "ISO 9000 §3.9.1",
    category: TermCategory.DEFINITIONS,
    domain: "Governance",
    source: "ISO 9000"
  },
  {
    id: "iso33",
    english: "Conformity",
    spanish: "Conformidad",
    englishDefinition: "fulfillment of a requirement",
    spanishDefinition: "cumplimiento de un requisito",
    reference: "ISO 9000 §3.6.1",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  },
  {
    id: "iso34",
    english: "Nonconformity",
    spanish: "No conformidad",
    englishDefinition: "non-fulfillment of a requirement",
    spanishDefinition: "incumplimiento de un requisito",
    reference: "ISO 9000 §3.6.2",
    category: TermCategory.DEFINITIONS,
    domain: "General",
    source: "ISO 9000"
  }
];
